name: Web build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build for production
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - run: npm ci
    - run: npm run dist

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: dist
        path: dist/*
        if-no-files-found: error
        retention-days: 1

    - name: HTTP Request Action
      uses: fjogeleit/http-request-action@v1.5.0
      with:
        url: "https://n8n.sixfoisneuf.fr/webhook/aurial-update"
        method: GET
